language: rust
env:
  global:
    secure: XUEuNCeOK0zMazSlY5ZbPeBH5RCvOX+xOGL6g96A3EAZJjGxBNe6j/7eYd8pKUebZt5c0lNYQ2oGwe754Zh8Y9F6JRhEkHWQGp9+SHmKKY7KpTcQGT6wAv5E0yJHyu4I+JX2lIbQDE623ti6r2PMV5XRnjyQ93wWdQVAijzTnaM=
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libmagic1 libmagic-dev
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=magic/index.html>' > target/doc/index.html &&
  pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
