[package]

name = "magic"
description = "libmagic bindings"
readme = "README.md"
license = "MIT"
keywords = ["magic", "binding", "file"]
homepage = "https://github.com/robo9k/rust-magic"
repository = "https://github.com/robo9k/rust-magic.git"
documentation = "https://robo9k.github.io/rust-magic/magic/"
authors = [
	"Daniel Micay <danielmicay@gmail.com>",
	"Petar Radošević <petar@wunki.org>",
	"lilydjwg <lilydjwg@gmail.com>",
	"Jeff Belgum <belgum@bastille.io>",
	"Onur Aslan <onur@onur.im>",
	"robo9k <robo@9k.lv>",
]
version = "0.10.0"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[lib]

name = "magic"

[dependencies]
magic-sys = "0.0.8"
bitflags = "0.3.0"
libc = "0.1.8"

[dev-dependencies]
regex = "0.1.38"
