[package]

name = "magic"
description = "libmagic bindings"
readme = "README.md"
license = "MIT"
keywords = ["magic", "binding", "file"]
homepage = "https://github.com/robo9k/rust-magic"
repository = "https://github.com/robo9k/rust-magic.git"
documentation = "http://rust-ci.org/robo9k/rust-magic/doc/magic/"
authors = [
    "Daniel Micay <danielmicay@gmail.com>",
    "Petar Radošević <petar@wunki.org>",
    "robo9k <robo@9k.lv>",
]
version = "0.6.1"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[lib]

name = "magic"

[dependencies]
magic-sys = "0.0.5"
