[package]

name = "magic"
description = "libmagic bindings"
readme = "README.md"
keywords = ["magic", "binding", "file"]
homepage = "https://github.com/robo9k/rust-magic"
repository = "https://github.com/robo9k/rust-magic"
documentation = "http://rust-ci.org/robo9k/rust-magic/doc/magic/"
authors = ["Daniel Micay <danielmicay@gmail.com>"]
version = "0.3.0"

[lib]

name = "magic"

[dependencies.magic-sys]
path = "magic-sys"
version = "0.0.1"
